### ISSUE TITLE
Sensor extension to combine some properties from EO and SAR extensions

### ISSUE THREAD

**Issue by matthewhanson** [radiantearth/stac-spec#555] opened 2019-08-15 20:13 UTC
Related to some of the discussion that happened at the beginning of #357, I was looking through the EO and SAR extensions for some commonalities. 

Pulling out these fields: 
- constellation
- platform
- instrument

into another extension serves not only the EO and SAR extensions but also future ones such as drones, or even ground based instruments.

- Constellation: a group of individual sensors often used together
- Platform: the unique ID of a single instrument
- Instrument: The name of the instrument

Eventually we might envision other fields such as sensor type (msi, sar, hyperspectral).

I'd also propose that this extension not use a prefix.

**Comment by m-mohr** [comment] 2019-08-16 11:12
Isn't this a duplicate of #356? Not sure whether we get this done for 0.8. There were some discussions on the STAC sprint 3, but we were stuck with some issues. Unfortunately, I can't recall what issues we faced. Do you remember, @jbants ?

**Comment by jbants** [comment] 2019-08-16 16:52
If I recall, we were starting to get into the issue of extension inheritance. If a user implements the `SAR` or `EO` extension are they required to implement the following non-prefix fields?

* constellation
* platform
* instrument

**Comment by matthewhanson** [comment] 2019-08-16 18:35
Hmm, yes this is somewhat of a duplicate, although I was moving away from a `sat` extension, because these 3 fields basically can apply to any sensor at all.

Not sure this needs to be for 0.8.0, but pulling stuff out of extensions and renaming things I'd rather we do sooner than later.

As far as extension inheritance....I'm not sure, should it be required?  I think so.   Someone could still have data where they didn't want to include details about the platform or instrument (perhaps it's sensitive info), but they could still just not populate those fields.

**Comment by matthewhanson** [comment] 2019-08-16 18:39
Also discussed in #356  is bands. The concept of bands is in both SAR and EO, but they contain some different fields.

But bands in general are really just variables, and any sensor is potentially capable of collecting data over multiple variables, so I could see it included more generally here as well, and with extensions adding fields to it.

**Comment by cholmes** [comment] 2019-08-18 22:55
I'm going to move this to 0.9.0, as I think we need to have a larger discussion on this and get a plan and philosophy of how to approach this. Overall I like the move, towards some 'core extensions' that don't need prefixes, but aren't in the absolute core. But we need to decide if it's one larger extension that lists all the non-prefix stuff, or a set of extensions with some special designation. I lean a bit towards the former to find them all in one place. 

I hear you on changing things earlier, but we do have decent versioning now so I don't think it should mess up too many people, and I think we should push out 0.8.0 asap.

**Comment by m-mohr** [comment] 2019-11-08 19:29
Closed as duplicate of #356.

**Closed by m-mohr** 2019-11-08 19:29 UTC
Labels: extension: eo, extension: sar, new extension, prio: should-have

**Comment by matthewhanson** [comment] 2019-11-19 18:25
Added with instrument extension (#658)
