### ISSUE TITLE
Decide how to describe "Product" level information for Assets and Items

### ISSUE THREAD

**Issue by lossyrob** [radiantearth/stac-spec#23] opened 2017-10-31 00:08 UTC
In the Boulder Sprint, we determined that there was some need to describe an Asset at the Product level, in that many Assets will be of the same type (e.g. NAIP RGBIR), and there should be one place to describe things like band information, license, etc. We should finalize how to handle the Product level information for Assets and Items.

**Comment by lossyrob** [comment] 2017-10-31 00:09
At the Boulder Sprint, I hacked together an example of working with NAIP data; in that I had a [field for "product" in the Asset properties](https://github.com/radiantearth/boulder-sprint/blob/master/specs/core-api/naip-example/naip-rgb-item.json#L36) that linked out to some [product JSON](https://github.com/radiantearth/boulder-sprint/blob/master/specs/core-api/naip-example/naip-product-rgb.json). This could be the way to do it; although an outstanding question would be, can an Item have product level info or should it always be attributed to an Asset?

**Comment by lossyrob** [comment] 2017-11-09 01:36
Proposal described [here](https://github.com/radiantearth/stac-spec/blob/feature/add-flat-file-spec/spec/json/README.md#asset)

**Comment by fredliporace** [comment] 2018-08-20 21:45
This is an old issue and some of the reference links are broken. Maybe close as a duplicate of #161?

**Comment by m-mohr** [comment] 2018-09-05 12:57
It is also a duplicate of #194 and actually solved by it. So this can be closed, I think.

**Closed by m-mohr** 2018-09-05 12:57 UTC
Labels: critical
