### ISSUE TITLE
File modification date in items

### ISSUE THREAD

**Issue by simonff** [radiantearth/stac-spec#241] opened 2018-09-06 04:42 UTC
Some providers regenerate files in-place several times, and storing file/asset modification date in the catalog file would speed up reads compares with querying each file individually. (Reading directory listings helps with speed, but directory listings are not standardized.)

**Comment by simonff** [comment] 2018-11-14 05:35
As discussed on gitter a bit, I think there is a need for a catalog listing that provides as little information as possible that still allows bulk mirroring of repos. Example:
{
  "type": "collection_manifest",
  "collection_id": "some_collection",
  "items": [
      "id": "item_id1",
       "assets":  {
          "B1": {
              "href": "https://site/some_collection/asset_id1_B1.tif",
              "mtime": "2010-02-03T04:05:06Z"
        },
   ]
}

**Comment by matthewhanson** [comment] 2019-03-27 04:27
I'm closing this as a duplicate of #351 , which suggest more fields but includes one for file modification. Feel free to discuss there.

**Closed by matthewhanson** 2019-03-27 04:27 UTC
Labels: duplicate
